### PR TITLE
github.com/confluentinc/confluent-kafka-go trace instrumentation 

### PR DESCRIPTION
**Pull request by Sreevani871**
Solving: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/88

- Trace instrumentation added for [confluent-kafka-go client](https://github.com/confluentinc/confluent-kafka-go).
- Added Dockerfile with example app showing instrumentation

**Note:** CI checks are failing due to cross compilation is not supported for the confluent-kafka-go package. [issue](https://github.com/confluentinc/confluent-kafka-go/issues/570)

### CODE REVIEW

**Comment by Sreevani871** [comment]
CI checks are failing due to confluent-kafka-go is not supporting cross compilation. Confirmed the same [here](https://github.com/confluentinc/confluent-kafka-go/issues/570). Is it fine to skip the tests for GOARCH 386 in makefile for CI checks to avoid ci checks failing? @Aneurysm9 Can you suggest what can be done regarding this issue?

**Review by jmacd — APPROVED** [review]

**Comment by Sreevani871** [comment]
@jmacd Can you suggest what can be done for CI checks fails?  And needs review.

**Comment by Sreevani871** [comment]
Hi, @Aneurysm9 We are looking forward to merging this PR. Looking forward to knowing what is the status of the PR, Can you please look into the PR and let us know if anything is missing? cc @jmacd @evantorrie

**Comment by eran-levy** [comment]
I think this PR is too old as channel based consumer is deprecated: https://github.com/confluentinc/confluent-kafka-go#channel-based-consumer-deprecated

Do you need help in updating this PR or I will create another PR with the newer version?

**Comment by Sreevani871** [comment]
> @jmacd @dashpole I think this PR is too old as channel based consumer is deprecated: https://github.com/confluentinc/confluent-kafka-go#channel-based-consumer-deprecated
> 
> Do you need help in updating this PR or I will create another PR with the newer version?

Hi, You can go ahead and create another PR with the newer version. 

> @jmacd @dashpole I think this PR is too old as channel based consumer is deprecated: https://github.com/confluentinc/confluent-kafka-go#channel-based-consumer-deprecated
> 
> Do you need help in updating this PR or I will create another PR with the newer version?
Hi, You can go ahead and create another PR with the newer version.

**Pull request closed without merging**
