### PR TITLE
Upgrade otel dependencies to v1.6.0/v0.28.0

### PR DESCRIPTION
**Pull request by MadVikingGod**
This will update all packages not effected by #1977

### CODE REVIEW

**Review by Aneurysm9 — APPROVED** [review]

**Comment by MrAlias** [comment]
Hmm, looks like there were some upgrades missed by multimod:

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/2f84ef6a0cfad022234d9abd1d9e1331bc59f227/instrumentation/github.com/astaxie/beego/otelbeego/go.mod#L15

I'm going to do a manual audit and push a fix.

**Comment by MrAlias** [comment]
Ah! Looks like all the missing upgrades are for what @MadVikingGod pointed out are the removed parts the metric upgrade.

```sh
grep -Rn 'go\.opentelemetry\.io/otel.*v' | grep -v 'v1\.6\.0' | grep 'go.mod' | grep -v 'go.sum' | grep -v 'v0.2[78].0' | cut -d: -f1
instrumentation/host/go.mod
instrumentation/net/http/otelhttp/test/go.mod
instrumentation/net/http/otelhttp/test/go.mod
instrumentation/net/http/otelhttp/test/go.mod
instrumentation/net/http/otelhttp/go.mod
instrumentation/net/http/otelhttp/go.mod
instrumentation/net/http/otelhttp/example/go.mod
instrumentation/net/http/otelhttp/example/go.mod
instrumentation/net/http/otelhttp/example/go.mod
instrumentation/net/http/otelhttp/example/go.mod
instrumentation/github.com/gocql/gocql/otelgocql/test/go.mod
instrumentation/github.com/gocql/gocql/otelgocql/test/go.mod
instrumentation/github.com/gocql/gocql/otelgocql/test/go.mod
instrumentation/github.com/gocql/gocql/otelgocql/go.mod
instrumentation/github.com/gocql/gocql/otelgocql/go.mod
instrumentation/github.com/gocql/gocql/otelgocql/example/go.mod
instrumentation/github.com/gocql/gocql/otelgocql/example/go.mod
instrumentation/github.com/gocql/gocql/otelgocql/example/go.mod
instrumentation/github.com/astaxie/beego/otelbeego/test/go.mod
instrumentation/github.com/astaxie/beego/otelbeego/go.mod
instrumentation/github.com/astaxie/beego/otelbeego/go.mod
instrumentation/github.com/astaxie/beego/otelbeego/example/go.mod
instrumentation/github.com/astaxie/beego/otelbeego/example/go.mod
instrumentation/github.com/astaxie/beego/otelbeego/example/go.mod
instrumentation/github.com/astaxie/beego/otelbeego/example/go.mod
```

**Comment by MrAlias** [comment]
Ran `go mod tidy`. It added missing dependency hashes. It also upgraded one dependency in otelbeego (`go.opentelemetry.io/otel`) as that was upgraded in one of its dependencies.

**Comment by srenatus** [comment]
Thank you 🎈

**Pull request merged**
