### PR TITLE
Remove deprecated exporters

### PR DESCRIPTION
**Pull request by MrAlias**

### CODE REVIEW

**Review by Aneurysm9 — APPROVED** [review]
😻

**Review by XSAM — APPROVED** [review]
🥇

**Review by pellared — APPROVED** [review]

**Comment by marco-m** [comment]
@MrAlias it seems that you forgot to update the README; it still contains
```
[Exporters](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/exporters): Packages providing OpenTelemetry exporters for 3rd-party telemetry systems.
```

**Comment by banks** [comment]
Hey heads up to say that this broke links in an AWS blog that is still linked from their main feature page under "how to ship metrics to AMP": https://aws.amazon.com/blogs/opensource/building-a-prometheus-remote-write-exporter-for-the-opentelemetry-go-sdk/

Linked here: https://aws.amazon.com/prometheus/features/

> To learn more about writing your own client to use remote write, see [Building a Prometheus remote write exporter for the OpenTelemetry Go SDK.](https://aws.amazon.com/blogs/opensource/building-a-prometheus-remote-write-exporter-for-the-opentelemetry-go-sdk/)

No idea if any of the contributors to that blog are likely to see this to help fix that but just wanted to call it out in case others are hunting around! If not I can see if that can be brought up with AWS folks somehow.

**Pull request merged**
