### PR TITLE
[otelhttp] add options to disable traces/metrics in otelhttp.NewHandler

### PR DESCRIPTION
**Pull request by RangelReale**
`otelhttp.NewHandler` handles both traces and metrics.

When we use other libraries for traces, for instance, `otelmux`, which doesn't have metrics, we would like to use the default metrics to be consistent, but currently it is not possible to use just metrics.

I tried to add a `noop` tracer provider option, but [it seems that it is not intended to be used this way](https://github.com/open-telemetry/opentelemetry-go/issues/4027).

This PR adds 2 new options: `WithDisableTraces` and `WithDisableMetrics`. The "disable" name is used to keep compatilibity with the default being "enabled".

### CODE REVIEW

**Comment by pellared** [comment]
Do we want to the same for:

- https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation/google.golang.org/grpc/otelgrpc
- https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation/github.com/gocql/gocql/otelgocql
- https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation/github.com/astaxie/beego/otelbeego

and potentially any future instrumentation libraries that would support both traces and metrics instrumentation?

**Comment by RangelReale** [comment]
> Do we want to the same for:
> 
> * https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation/google.golang.org/grpc/otelgrpc
> * https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation/github.com/gocql/gocql/otelgocql
> * https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation/github.com/astaxie/beego/otelbeego
> 
> and potentially any future instrumentation libraries that would support both traces and metrics instrumentation?

Or maybe having 2 separate handlers, one for traces and one for metrics, and a "combined" one which has both, and keeps compatibility with the current one?

**Comment by dmathieu** [comment]
Related proposal: #2782.

**Comment by pellared** [comment]
Closing per https://github.com/open-telemetry/opentelemetry-go/issues/4027#issuecomment-1527170258

**Pull request closed without merging**
