### PR TITLE
Deprecate otelmongo/test

### PR DESCRIPTION
**Pull request by MrAlias**
Part of #5551

Follow up to a missing change not included in #5598. We want to deprecate `otelmongo` and `otelmongo/test` at the same time.

### CODE REVIEW

**Review by pellared — APPROVED** [review]

**Review by dashpole — APPROVED** [review]
Non-blocking: WDYT of not including a changelog entry for this PR, and changing the doc.go to say that otelmongo (instead of test) has no codeowner.  I don't think it really makes sense to separately call for a CODEOWNER of the test directory.

**Comment by MrAlias** [comment]
> Non-blocking: WDYT of not including a changelog entry for this PR, and changing the doc.go to say that otelmongo (instead of test) has no codeowner. I don't think it really makes sense to separately call for a CODEOWNER of the test directory.

I'm onboard for this if others are. @pellared?

**Comment by pellared** [comment]
I support  @dashpole proposal

**Comment by MrAlias** [comment]
Updated, PTAL

**Review by dashpole — APPROVED** [review]

**Review by pellared — APPROVED** [review]

**Review by dmathieu — APPROVED** [review]

**Pull request merged**
