### PR TITLE
Use lychee cache

### PR DESCRIPTION
**Pull request by dmathieu**
A few months ago, we enabled lychee cache in the SDK repo, to prevent rate limit issues, but forgot to enable it here.
https://github.com/open-telemetry/opentelemetry-go/pull/5160

### CODE REVIEW

**Comment by dmathieu** [comment]
Note that the check needs to succeed once for the cache to be stored (lychee doesn't update the cache if there's a failure anyway).

**Review by pellared — APPROVED** [review]

**Comment by pellared** [comment]
@dmathieu, this does not look like fixing the following issue:

> * [429] [https://github.com/open-telemetry/opentelemetry-go/commits/main](https://github.com/open-telemetry/opentelemetry-go/commits/main) | Failed: Network error: Too Many Requests

**Comment by dmathieu** [comment]
The check needs to run successfully once (we can trigger it at a moment of low activity) to trigger the cache.

**Comment by pellared** [comment]
> add an auth token to the GitHub requests so the rate limit is increased

I think this is the way. We just need to make sure to limit the permissions for `GITHUB_TOKEN` using https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token#defining-access-for-the-github_token-permissions

Reference: https://github.com/lycheeverse/lychee/blob/master/docs/TROUBLESHOOTING.md

**Review by pellared — APPROVED** [review]

**Review by dashpole — APPROVED** [review]

**Pull request merged**
