### PR TITLE
Cherrypick #2983: treat http.NoBody the same as a nil body

### PR DESCRIPTION
**Pull request by dashpole**
Part of https://github.com/open-telemetry/opentelemetry-go-contrib/issues/3513

### CODE REVIEW

**Review by MrAlias — APPROVED** [review]

**Review by Aneurysm9 — APPROVED** [review]
Will also need  a PR to `main` adding the changelog entry.

**Comment by dashpole** [comment]
do I also need to update otelhttp version.go?  do I need to update version.yaml?  Or should I leave the changelog as Unreleased?

**Comment by MrAlias** [comment]
> do I also need to update otelhttp version.go? do I need to update version.yaml? Or should I leave the changelog as Unreleased?

Good question. I think `version.go` needs to be updated in the `otelhttp` directory.

I'm not sure `version.yaml` needs to be updated as I plan on tagging this outside of our tooling.

The changelog looks good to me given this is the end of the road for this branch's development.

**Comment by dashpole** [comment]
Updated version.go

**Pull request merged**
