### PR TITLE
update gin services name key is service.name

### PR DESCRIPTION
**Pull request by andotorg**
fix  [#4476](https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4476)

### CODE REVIEW

**Comment by pellared** [comment]
This change is not compliant with the OpenTelemetry Specification. See https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4476#issuecomment-1777870968 for more info.

**Comment by MrAlias** [comment]
> This change is not compliant with the OpenTelemetry Specification. See [#4476 (comment)](https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4476#issuecomment-1777870968) for more info.

Agreed. Thank you @andotorg for taking the time to contribute. However, we are not able to accept these changes as they do not comply with the OpenTelemetry semantic conventions. Closing.

**Comment by andotorg** [comment]
@MrAlias 
Sorry, I cannot accept your opinion. Are you saying that `jaeger` was not developed according to the specifications?
router.Use(otelgin.Middleware("foobar", otelgin.WithTracerProvider(provider)))   
`foobar` will not be displayed in the jaeger service list, then you think it does not comply with the specification, but at the display level the service list is `service.name`, a service cannot be displayed to users as a service using `net.host.name` Check? Do you think this is reasonable?

**Comment by andotorg** [comment]
Sorry, It is not in compliance with the standard. I think it can be changed to follow the standard. I hope that the value of this parameter can be displayed normally in `jaeger`. Should I deal with `otelgin` again?

**Pull request closed without merging**
