### PR TITLE
Fix issues raised by golangci-lint

### PR DESCRIPTION
**Pull request by krnowak**
These popped up when invoking `make`.

### CODE REVIEW

**Comment by lizthegrey** [comment]
Can you modify the circleci config to ensure it checks these?

**Comment by lizthegrey** [comment]
I just fixed our Circle config to automatically build this, can you amend and --force push it to make it update?

**Comment by lizthegrey** [comment]
yeah, you'll need to integrate https://github.com/open-telemetry/opentelemetry-go-contrib/pull/30 in order to verify this fixes the build.

**Comment by lizthegrey** [comment]
Checks passed, is safe to merge.

**Comment by krnowak** [comment]
@lizthegrey : Thanks for handling this - I was busy reviewing mongo db PR at the time and haven't noticed your replies. Also, I assumed that CI was not yet set up. Good to know that I was wrong.

**Pull request merged**
