### PR TITLE
Add registry link check target to Makefile

### PR DESCRIPTION
**Pull request by matej-g**
This PR is a proposal which addresses #380, i.e. creation of mechanism to check whether all plugins included within `contrib` repository have a valid link in the [OpenTelemetry Registry](https://github.com/open-telemetry/opentelemetry.io/tree/master/content/en/registry).

The proposal adds a target to the `Makefile`, which checks the links by querying individual `.md` files representing entries in the registry and ensuring these are up to date in the following manner:

1. Each plugin should have a properly structured filename in the registry, which should have the format `<plugin_type>-go-<name>.md`, where:
- `plugin_type` should be one of `instrumentation`, `exporter` or `detector`
- `name` is the name of the actual plugin package (stripped of `otel` prefix, if there is one)

2. The links in the registry should point to `master` and lead to:
- In case of `instrumentation`, to directory which is identical with the import path of the instrumented package (e.g. for `github.com/gorilla/mux` it should be `https://github.com/open-telemetry/opentelemetry-go-contrib/tree/master/instrumentation/github.com/gorilla/mux`)
- In case of other plugins, to the directory of the module (where `go.mod` resides)

This will require also adjusting current entries in the registry, as not all file names adhere to this proposed format.

If the check it unsuccessful, it prints out a warning with the list of plugins, which do not have up to date links. The check should be run as a part of the pre-release script.

Still to decide:
~~- Should this target be run as a part of the pre-release script? Should it be left to the maintainers discretion to run it?~~

### CODE REVIEW

**Comment by evantorrie** [comment]
> * `plugin_type` should be one of `instrumentation`, `exporter` or `tool` (plugins under `detector` or other plugins which might not fit into the first two categories)

 My one nit here is whether we should have a catchall `tool`, or instead, just have another type called `detector` for now, and add other "types" as and when we run into them.

> Still to decide:
> 
> * Should this target be run as a part of the pre-release script? Should it be left to the maintainers discretion to run it?

I don't think it should *block* the pre-release script, but it would be good for it to kick out a warning about "hey, some plugins are not registered".  To fix erroneous entries will require creating a PR against the registry repo and getting it merged.  While response to registry PRs has usually been quick in my experience, I don't think it should be a blocker to our releasing a new version.

**Comment by matej-g** [comment]
> My one nit here is whether we should have a catchall `tool`, or instead, just have another type called `detector` for now, and add other "types" as and when we run into them.

I'm fine with having only `detector` for now. I was conflating this with the categorization they have in the registry, but looks like we can keep the filename independent of registry category and including tags in the `.md` should take care of this (should be `utilities` component).

> I don't think it should _block_ the pre-release script, but it would be good for it to kick out a warning about "hey, some plugins are not registered". To fix erroneous entries will require creating a PR against the registry repo and getting it merged. While response to registry PRs has usually been quick in my experience, I don't think it should be a blocker to our releasing a new version.

Warning in pre-release sounds good :+1:

**Comment by matej-g** [comment]
Thanks for the suggestions @evantorrie, these have now been applied. Opening the PR for wider review.

**Review by Aneurysm9 — APPROVED** [review]

**Review by MrAlias — APPROVED** [review]

**Comment by MrAlias** [comment]
@evantorrie can you take another look?

**Comment by matej-g** [comment]
Any update on this one? Shall we proceed?

**Pull request merged**
