### PR TITLE
Fix bug: cannot parse import comment

### PR DESCRIPTION
**Pull request by Hellcatlk**
Signed-off-by: zouyu <zouy.fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by Aneurysm9** [comment]
Can you provide more details about the error this is intended to address?  I don't believe that I have seen any errors with the import statement here.  Would this change also need to be applied to all other packages that specify a canonical import location?

**Comment by Hellcatlk** [comment]
go version: 1.15

When i import this package, and compile program:

```
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/doc.go:1: cannot parse import comment
```

**Comment by Aneurysm9** [comment]
Interestingly, after some experimentation I was able to reproduce this error only when using `go get` not in module mode.

@Hellcatlk once you get the CLA authorization handled please comment on this issue to clear the blocker.  Thanks.

**Review by Aneurysm9 — APPROVED** [review]

**Review by XSAM — APPROVED** [review]

**Review by MrAlias — APPROVED** [review]

**Comment by Hellcatlk** [comment]
Sorry, I am waiting the Fujitsu's CLA, this may take some time.

**Pull request closed without merging**
