### PR TITLE
Support graphql tracing

### PR DESCRIPTION
**Pull request by jjmengze**
Open Tracing instrumentation for the graphql ,By default it starts a new span for every request handled by graphql. It follows the open tracing tagging semantic conventions.

### CODE REVIEW

**Comment by jjmengze** [comment]
resolve #85

**Comment by jjmengze** [comment]
@Aneurysm9 @MrAlias Please take a look whenever you get a chance.

**Comment by MrAlias** [comment]
This does not instrument https://github.com/graph-gophers/graphql-go, what #85 is tracking.

**Comment by jjmengze** [comment]
@MrAlias could you please let me know why this is not an instrument.

Not only graphql-go but also [gqlgen](https://github.com/99designs/gqlgen) provide GraphQL servers. Those ecosystem (graphql-go,gqlgen) seems to me like gin and echo.

**Comment by jjmengze** [comment]
Correctly speaking, this pr is not for graphql-go.

**Comment by MrAlias** [comment]
Can you convert this to a draft and fix the build/lint errors and comment all exported objects. This does not look ready for review.

**Comment by jjmengze** [comment]
@MrAlias Sincerely thank you for your suggestions, I have fixed them.

**Comment by jjmengze** [comment]
@MrAlias Sincerely thank you for your suggestions, I have fixed them.

**Comment by ravilushqa** [comment]
gqlgen pr already here
https://github.com/open-telemetry/opentelemetry-go-contrib/pull/761

**Comment by jay-manday** [comment]
We really would like to see this merged it's a major blocker for us

**Comment by pellared** [comment]
@ravilushqa @jay-manday @jjmengze 
Could you please collaborate and make one of your PRs as a draft to make the reviewers' life easier? 😉

**Comment by pellared** [comment]
Closing this one as https://github.com/open-telemetry/opentelemetry-go-contrib/pull/761 was first and it is in better shape.

Anyway thanks for the PR ❤️

**Pull request closed without merging**
