### PR TITLE
otelhttptrace: get tracer from request if available

### PR DESCRIPTION
**Pull request by tonistiigi**
Similar change as #873 for `otelhttptrace`. Picks up the correct `TracingProvider` based on parent span in the config.

@Aneurysm9 

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Comment by tonistiigi** [comment]
Marking as draft so changelog can be updated after #873 merge . If I do it now it will cause a conflict.

**Comment by thaJeztah** [comment]
@tonistiigi https://github.com/open-telemetry/opentelemetry-go-contrib/pull/873 was merged; guess this needs to be rebased and moved out of draft

**Review by pellared — APPROVED** [review]

**Comment by thaJeztah** [comment]
@XSAM @Aneurysm9 this one LGTY?

**Review by XSAM — APPROVED** [review]

**Review by MadVikingGod — APPROVED** [review]

**Comment by crazy-max** [comment]
@pellared @XSAM @MadVikingGod Is there a blocker to merge this one? Thx!

**Comment by MrAlias** [comment]
@dependabot rebase

**Pull request merged**
