### PR TITLE
Modified otel-http-server-duration from microseconds to milliseconds

### PR DESCRIPTION
**Pull request by rltoSD**
Description:
This PR is to modify otel http server duration from microseconds to milliseconds as per the specs mentioned in OpenTelemetry Go.

Link to tracking Issue:
issue #1335

### CODE REVIEW

**Review by Aneurysm9 — APPROVED** [review]
Please add a `CHANGELOG.md` entry.

**Review by XSAM — APPROVED** [review]

**Review by dashpole — APPROVED** [review]

**Review by pellared — APPROVED** [review]

**Review by jmacd — APPROVED** [review]

**Comment by MadVikingGod** [comment]
Just for my curiosity why was there a change from int64 to float64?

**Comment by rltoSD** [comment]
@Aneurysm9 Updated changelog & ready to be merged now

**Comment by Aneurysm9** [comment]
> Just for my curiosity why was there a change from int64 to float64?

It changed from integer microseconds to float milliseconds.  The float is necessary because integer millisecond granularity is very coarse and, in my experience, not sufficient.

**Comment by Aneurysm9** [comment]
> @Aneurysm9 Updated changelog & ready to be merged now

The CLA still needs to be resolved.

**Comment by rltoSD** [comment]
> [CLA Not Signed](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/9522512/242202166/1414/#/?version=2)
> 
> * ✅  Richard To ([2e425ed](https://github.com/open-telemetry/opentelemetry-go-contrib/commit/2e425ed77d7182eb765d90f540dd2b0fab0d140b), [84f75fa](https://github.com/open-telemetry/opentelemetry-go-contrib/commit/84f75fabe56534b492f34c7c79d802b1b4b91c02), [a2d146f](https://github.com/open-telemetry/opentelemetry-go-contrib/commit/a2d146f25ac353cce5da5fe78a8b9d227caa6f65))
> 
> * ❌ The commit ([b23dca3](https://github.com/open-telemetry/opentelemetry-go-contrib/commit/b23dca3f59444d62335611c202ffcd0942e0d550)) is missing the User's ID, preventing the EasyCLA check. [Consult GitHub Help](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user) to resolve.For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

signed the CLA; awaiting update

**Comment by MadVikingGod** [comment]
For it to pass you will have to change this PR so that commit `b23dca3` has
your username/email as the author, and force push the new history.
Alternatively you could squash all of your commits, only because we will
lose the conversation history anyways.

**Pull request closed without merging**
