### PR TITLE
add instrumentation for beego v2

### PR DESCRIPTION
**Pull request by tonyttz**

### CODE REVIEW

**Comment by tonyttz** [comment]
Add instrumentation for github.com/beego/beego v2

**Comment by mm2175** [comment]
Any update on this?

**Comment by dmathieu** [comment]
Sorry for the lack of response here.
Approving this new instrumentation would require more details, especially with the documentation provided here: https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation#new-instrumentation

**Comment by pellared** [comment]
The latest version of beego already has some OTel support e.g. https://pkg.go.dev/github.com/beego/beego/v2/client/httplib/filter/opentelemetry and https://pkg.go.dev/github.com/beego/beego/v2/client/orm/filter/opentelemetry

I have a strong feeling that https://github.com/beego/beego is the right place for the new instrumentation.

I think you can consider reopening https://github.com/beego/beego/issues/4945 (or creating a duplicate).

**Pull request closed without merging**
