### PR TITLE
config: add yaml/json struct tags

### PR DESCRIPTION
**Pull request by codeboten**
This will make parsing the configuration easier

### CODE REVIEW

**Comment by MadVikingGod** [comment]
This needs a changelog.

I see this adds additional tags, but I'm not 100% sure how this is used. It doesn't necessarily need to be part of the PR, but could you share an example of how this was used before and how it works now?

**Comment by pellared** [comment]
Can you add tests that verify that the YAML/JSON files are parsed (thanks to the tags) as expected?

**Comment by codeboten** [comment]
@MadVikingGod @pellared happy to add some functionality to test it, i didn't want to overstep on this PR https://github.com/open-telemetry/opentelemetry-go-contrib/pull/4826

@carrbs if you're ok with it I can incorporate your work here, or you can pull this change in your PR, it's all the same to me :)

**Comment by carrbs** [comment]
> @MadVikingGod @pellared happy to add some functionality to test it, i didn't want to overstep on this PR #4826
> 
> @carrbs if you're ok with it I can incorporate your work here, or you can pull this change in your PR, it's all the same to me :)

I'm good with incorporating here, thanks @codeboten!

**Comment by MadVikingGod** [comment]
So, what I was hoping for to understand better why this change is necessary was something like:
Before:
```go
input := map[string]interface{}
err := json.Unmarshal(rawJson, &input)
config := config{}
err = mapstructure.Decode(input, &config)
```

But afterwards we have
```
Some happy path code
```

While this looks to add direct ways to decode directly into our Config structures, it also means we have to test three different decoders (Mapstructure, Json, and Yaml) and find all the edge cases of each.

**Review by bogdandrutu — APPROVED** [review]

**Review by MrAlias — APPROVED** [review]

**Review by pellared — APPROVED** [review]

**Comment by MrAlias** [comment]
@MadVikingGod PTAL

**Comment by codeboten** [comment]
Added test to validate json/yaml parsing is working as expected, also pulled in part of https://github.com/open-telemetry/opentelemetry-go-contrib/pull/4826 for adding a ParseYAML api

**Review by pellared — APPROVED** [review]

**Pull request merged**
