### PR TITLE
otelgrpc: add WithMeterProvider option

### PR DESCRIPTION
**Pull request by codeboten**
Adding the ability to set a MeterProvider to `otelgrpc` instrumentation for future use.

### CODE REVIEW

**Comment by bogdandrutu** [comment]
@codeboten please rebase

@Aneurysm9 @MrAlias please help us with this PR.

**Review by jmacd — APPROVED** [review]

**Review by pellared — APPROVED** [review]

**Review by Aneurysm9 — APPROVED** [review]

**Review by pellared — APPROVED** [review]

**Comment by bogdandrutu** [comment]
@codeboten you need another rebase

**Comment by codeboten** [comment]
@bogdandrutu I'm not seeing anything needing rebase in github 🤔 i did rebase yesterday though.

**Comment by MrAlias** [comment]
@codeboten do you have a plan or design doc/issue for the future metric instruments planned to be added here? Is this a PR you plan to submit after this?

I want to be sure we don't couple this instrumentation to the unstable metrics signal without a plan forward with how it will be used.

**Comment by codeboten** [comment]
> @codeboten do you have a plan or design doc/issue for the future metric instruments planned to be added here? Is this a PR you plan to submit after this?
> 
> I want to be sure we don't couple this instrumentation to the unstable metrics signal without a plan forward with how it will be used.

The metrics I would expect we would want out of this instrumentation would likely be what's defined in the spec [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/rpc.md#metric-instruments).

This PR is specifically to allow the grpc instrumentation to configure a meter provider in the collector (see https://github.com/open-telemetry/opentelemetry-collector/issues/4030) as we have the ability for today with the tracer provider.

I don't immediately plan on adding metrics to the instrumentation as you mentioned the stability isn't there yet, but i can add an issue and follow up on it at a later time if that works for you.

**Comment by codeboten** [comment]
@MrAlias is there a way to move this PR forward or would you prefer to close it and reinstate when the metrics api is stable? I'm not sure how to move forward at this point.

**Comment by bogdandrutu** [comment]
@MrAlias @codeboten the metrics API is stable, let's move forward with this PR :)

**Comment by MrAlias** [comment]
It looks like https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2700 supersedes this, closing. Please reopen if this was in error.

**Pull request closed without merging**
