### PR TITLE
add span name generator for otelgin option

### PR DESCRIPTION
**Pull request by jojotong**

### CODE REVIEW

**Comment by dmathieu** [comment]
I think this should be named WithSpanNameFormatter, to match the net/http config.
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/net/http/otelhttp/config.go#L189

**Comment by jojotong** [comment]
> I think this should be named WithSpanNameFormatter, to match the net/http config.

Thanks for notice, I've changed to to match the net/http config

**Review by hanyuancheung — APPROVED** [review]

**Review by dmathieu — APPROVED** [review]

**Comment by dmathieu** [comment]
@jojotong could you fix the tests, lint and add a changelog entry?

**Comment by jojotong** [comment]
@dmathieu fixed.

**Comment by jojotong** [comment]
Rebased to resolve conflicts.

**Pull request merged**
