### PR TITLE
Add support for Iris

### PR DESCRIPTION
**Pull request by kataras**

### CODE REVIEW

**Comment by dmathieu** [comment]
Hi, and thank you for this contribution.
Could you elaborate on why this must be located in this repository and not within the project itself, or a repo on your own account?
See https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/README.md#new-instrumentation

**Comment by kataras** [comment]
Hello @dmathieu, 

I didn't get it, why should I create an external repository where this repository is hosting other Go web frameworks already? I am just adding support for one more popular web framework.

**Comment by kataras** [comment]
Hello @dmathieu,

I didn't create an external repository because this repository is hosting other Go web frameworks already, I am just adding support for one more popular web framework. However, I have to read the document you provided, maybe I need to fill a specific form on your organization before this PR merge.

**Comment by 2292384454** [comment]
> Hello @dmathieu,
> 
> I didn't create an external repository because this repository is hosting other Go web frameworks already, I am just adding support for one more popular web framework. However, I have to read the document you provided, maybe I need to fill a specific form on your organization before this PR merge.



> _ No description provided. _

It's useful!
if it's not allowed to be here, would you add it in iris/middleware? I really need it!

**Comment by dmathieu** [comment]
You're welcome to host and maintain it yourself on a repository in your own account ;)

**Comment by pellared** [comment]
Closing per https://github.com/open-telemetry/opentelemetry-go-contrib/pull/3579#issuecomment-1466260980

**Pull request closed without merging**
