### PR TITLE
instrgen fixing imports

### PR DESCRIPTION
**Pull request by pdelewski**
Remove import that only is needed in `main.go` from the other test data files so it will not fail the build.

### CODE REVIEW

**Comment by pellared** [comment]
How about removing `//nolint:all` and addressing all the issues? Would it be too much?

**Comment by pdelewski** [comment]
> How about removing `//nolint:all` and addressing all the issues? Would it be too much?

`//nolint:all` was added for different reason. Linter is executed at the same time as tests which leads to race conditions and failures

**Comment by MrAlias** [comment]
Why are these imports removed?

**Comment by MrAlias** [comment]
It looks like the tests are failing. Can you take a look at the data race?

**Comment by pdelewski** [comment]
> Why are these imports removed?

This import is needed only in `main.go`, they are leftovers and if you will try to build this test program compiler will complain about unused imports

**Comment by pdelewski** [comment]
> It looks like the tests are failing. Can you take a look at the data race?

They are unrelated to `instrgen`

**Review by MrAlias — APPROVED** [review]

**Review by pellared — APPROVED** [review]

**Comment by pellared** [comment]
> > How about removing `//nolint:all` and addressing all the issues? Would it be too much?
> 
> `//nolint:all` was added for different reason. Linter is executed at the same time as tests which leads to race conditions and failures

Then it would be good to add the reason in a comment e.g. like `//nolint:all // Linter is executed at the same time as tests which leads to race conditions and failures.` Possibly also track it in some issue to resolve it at some point.

**Comment by pdelewski** [comment]
> > > How about removing `//nolint:all` and addressing all the issues? Would it be too much?
> > 
> > 
> > `//nolint:all` was added for different reason. Linter is executed at the same time as tests which leads to race conditions and failures
> 
> Then it would be good to add the reason in a comment e.g. like `//nolint:all // Linter is executed at the same time as tests which leads to race conditions and failures.` Possibly also track it in some issue to resolve it at some point.

Good point.

**Pull request merged**
