### PR TITLE
Move Aneurysm9 to emeritus status

### PR DESCRIPTION
**Pull request by Aneurysm9**
I have been unable to provide this position the bandwidth that it deserves and it is time to formalize recognition of that fact.

### CODE REVIEW

**Review by dashpole — APPROVED** [review]
Should we open issues to track the components that are now missing CODEOWNERS?  Or do we know of anyone who would be a good fit?

**Review by pellared — COMMENTED** [review]
Fist of all, thanks for your contributions to the project 🙏 

If it is not you then are you able to find someone in AWS who could be a codeowner of AWS detectors and instrumentations?

**Review by MrAlias — APPROVED** [review]

**Comment by Aneurysm9** [comment]
I have some people internally I'm going to reach out to about taking the code owner role for the AWS components in this repo, but don't have any names to give at this time.  If you'd like me to keep my name on them in the interim I can do so, but will be responsive on a best-effort basis.

**Comment by pellared** [comment]
>  If you'd like me to keep my name on them in the interim I can do so, but will be responsive on a best-effort basis.

I think it will be a lot better than having nobody.

**Review by MadVikingGod — APPROVED** [review]

**Review by dmathieu — APPROVED** [review]

**Review by pellared — APPROVED** [review]

**Pull request merged**
